UCF/Today-Child-Theme

- dev/acf-export.json
Created new ACF fields for posts (stories) that will replace the custom fields that were created in the old theme. I organized them with tabs (similar to how we do with the Page Header Fields). Let me know if anyone has better ideas for organizing them or improvements to the naming conventions. I also updated the 'Page Header Fields' to not display on Posts. I figured we would still want these in this theme for Pages.
Post custom fields in the old theme needed to be 'ACF-ized'. 
New field settings are viewable in Dev under Custom Fields, and also when editing posts.
**Checklist:**
> Created ACF Post Fields

- archive.php
- dev/acf-export.json
- includes/header-functions.php
- template-parts/header-section.php
- template-parts/header_content-section.php
- template-section.php
- Adds the Section template for pages and custom header and header content template parts specifically for the section template.
- Removes the ACF 'Page Header Fields' from displaying on pages with the Section template selected since the section pages should all have a similar heading style for consistency. If in a future sprint these pages get re-designed or need custom fields, we can add them back in or create a new group of custom fields specifically for what this template type requires.
- Removes 'Archives' from being listed as a template type option.
These are updates that will be included in Sprint 1 of the Today Theme rebuild.
Reviewable in dev.
**Checklist:**
> Section Page Template

- dev/acf-export.json
- includes/header-functions.php
- template-category.php
- template-parts/header-category.php
- template-parts/header_content-archive.php
- template-parts/header_content-category.php
See title.
We decided to use the name 'category' instead of 'section' in order to more closely align with what is actually being displayed on these templates and pages and so that we do not have naming conflicts or confusions with the UCF Section plugin. 
Also, updated the comment for the `header_content-archive.php` file.
Changes viewable in dev.
**Checklist:**
> Rename the 'section' template to 'category'

- includes/features.php
- includes/post-functions.php
Replaces usage of `wp_get_attachment_image()` within the theme with `ucfwp_get_attachment_image()`.
Depends on https://github.com/UCF/UCF-WordPress-Theme/pull/54.
Ensures that thumbnails in features and post header images don't contain `srcset` values that force the browser to load a larger image than we expect.
**Checklist:**
> Responsive image srcset maximum widths

- dev/acf-export.json
- functions.php
- includes/category-functions.php
- template-category.php
Adds ACF fields to the Category template pages which enable the use of a sidebar. The sidebar contents can be added, removed, and re-arranged per page. The sidebar 'sections' included are: events, in the news, resources menu,  a spotlight (which uses posts from the UCF Spotlights plugin), and custom content. The UCF Spotlights plugin has been installed in order to utilize those instead of creating something custom for category pages.
**NOTE:** I've started working on making some of the options customizable in the ACF fields, example: the Events shortcode feed URL, layout, limit, etc. Those updates will be included in a separate PR.
Trying to improve the use of the same content in the sidebar across all Category pages, while keeping each page …
> Category Page Sidebar Enhancements

- includes/utilities.php
Adds the utility function `today_get_thumbnail_url()`, which returns a post's thumbnail URL by size, and optionally a fallback if no image is available.
This new function and `today_get_thumbnail_id()` now also accept a post ID in the `$post` arg (instead of just a `WP_Post` object) to help support the Today Utilities plugin, which needs to be able to pass in a post ID.
A separate function that returns an image URL, and not just an attachment ID, is necessary for the Today Utilities plugin to be able to utilize header video poster images as story thumbnails.
**Checklist:**
> Thumbnail URL utility function

- dev/acf-export.json
- includes/config.php
- includes/post-functions.php
Adds a read-only "Published Date" field to the Post Custom Fields. This will be used to output the original date, vs. a newer "updated date" (which will be controlled by the `post_date` field).
Editors need the ability to update stories and indicate that they've been updated. They also need the stories list to be ordered by the "updated" dates. It was inefficient to use a postmeta field for the updated date as this required an expensive join in order to do a proper orderby clause, so the built in `post_date` will now represent the updated date and the `post_header_publish_date` will represent the original publish date.
Changes can be seen in dev.
**Checklist:**
> Originally posted

- category.php
- includes/header-functions.php
- Adds a template for non-top-level categories.  It's effectively identical to `tag.php`.
- Adds " News" to the end of category and tag archive h1 text to match top-level category pages.
To support non-top-level category archives.
**Checklist:**
> Category template, h1s

- includes/config.php
Unregisters the UCF WP Theme's header media image sizes.
Since media headers aren't used in this theme, these image sizes aren't necessary.  Removing them prevents generation of a bunch of unused images whenever new media is uploaded to the media library.
**Checklist:**
> Remove unused image sizes

- includes/tag-cloud-functions.php
Fixed display of tag clouds on stories that don't have an explicit `post_display_tag_cloud` field value.
We expect tag clouds to be displayed on all stories by default, unless explicitly disabled.
**Checklist:**
> Tag cloud fix

- dev/acf-export.json
- Renamed Syndication Fields metabox to "Main Site News"
- Updated permissions on the metabox so that superadmins can view it when editing posts
- Renamed per Laura's request
- Super admins couldn't view the metabox
Reviewable in Dev
**Checklist:**
> Renamed Syndication Fields metabox; updated permissions so that superadmins have access to it

- includes/post-functions.php
Removes logic when fetching a post's header image that tries to accommodate for Today-Bootstrap image sizes.  This logic now assumes that all image thumbnails have been regenerated, and that fetching a thumbnail by its size name will return the dimensions registered in this theme.
In some cases, stories would display extremely large images if the existing 'large' size was smaller than the child theme's registered dimensions--resulting in the next size up, 'full', being returned instead.
This update assumes thumbnails have been regenerated to work around this problem.
Reviewable in Dev post-thumbnail regeneration.
**Checklist:**
> Header image sizes

- dev/acf-export.json
- includes/features.php
- includes/utilities.php
See title.  This update also removes the 500KB filesize limit on header images, which maybe confusing with the sitewide limit for images (800KB).
The content team has expressed interest in being able to add some sort of adjustment to video story thumbnails to indicate that there's a video to play.  Enabling the header image field for video stories will allow users to upload a custom thumbnail, while still displaying the large video when viewing the single story.
**Checklist:**
> Added ability to specify a custom thumbnail image for stories with a header video

- includes/post-functions.php
- includes/utilities.php
- Added hooks that modify post author display names on the site frontend.  Functions for displaying single posts now use vanilla WP author-fetching functions when grabbing author names.  This update has the added benefit of making AMP layout author data consistent with the site frontend.
- Added hook that modifies a post's enclosure value, which is used in RSS/Atom fields to represent the post's thumbnail.  RSS feed thumbnails should now be accurate with what's displayed on the frontend.
- Fixed bug in `today_get_thumbnail_url` that would result in posts using a header video and custom thumbnail image displaying the wrong thumbnail
Helps fix consistency issues between the site frontend and feed data.
Reviewable in …
> Updates for feed compatibility

- includes/archive-functions.php
Ensures that the dates used to determine the previous and next archive links are created using the 1st day of the month to avoid a bug where invalid dates are created.
Currently it's possible that month links can bug out when the code runs towards the end of the month. PHP uses the current day of the month when creating dates and a specific day isn't provided. This can lead to dates like `02/31/2019` being created, which is an invalid date and leads to some unexpected behavior.
The change is available in DEV and QA for review.
**Checklist:**
> Hf archives

- includes/config.php
See title.
Since the Resource Link CPT is used for managing external stories on Today, having this default term set makes it easier for content editors and eliminates an extra step for them when creating new Resource Links.
**Checklist:**
> Force default Resource Link Type term on Resource Links

- includes/post-functions.php
Ensures an empty `post_header_publish_date` is not displayed on the front end. Updating the `isset` check to `! empty` handles the empty string bug when the post is saved as a draft (before it's been published).
When working on stories, the writers were noticing an "Originally Published: Jan 1, 1970" in the heading. This was happening because the `post_header_publish_date` meta value is not set with a proper value until the post is published, but is saved as an empty string. An empty string passed into the PHP `Date` class will evaluate at 1/1/70. 
The changes is available in dev and can be tested using the steps outlined in Issue #72.
**Checklist:**
> Updated display logic not to show original date when it's empty

- includes/utilities.php
Wraps Juxtapose oEmbed content in a responsive embed wrapper, and modifies width and height values on the generated iframe.
While Juxtapose provides some out-of-the-box responsiveness, it tends to not calculate its embed height values very well.  Wrapping the embed in an `.embed-responsive` wrapper, as well as adjusting the width and height to a 16x9 ratio (768x410px), ensures the embed is sized appropriately on all screen sizes.
Note that, even with this update, the Juxtapose embeds still force a fixed width, so after resizing the page, the embed will clip in the embed wrapper instead of scaling down.  However, after refreshing the page, the dimensions will be recalculated. …
> Added sizing adjustments to Juxtapose oEmbed content

- includes/excerpts.php
- includes/features.php
Moved post type-specific excerpt overrides into a new `get_the_excerpt` hook, which ensures that native WordPress features that utilize excerpts (such as REST APIs) will consistently display overridden values (e.g. decks for stories).
With this update, `today_get_excerpt()` no longer behaves differently than the UCF WordPress Theme's `ucfwp_get_excerpt()`, and its usage has been replaced in the theme.
Requested by Laura to ensure main site stories displayed on ucf.edu use decks instead of auto-generated excerpts.
Tested + reviewable in Dev.
**Checklist:**
> Consistent excerpt values

- includes/config.php
Ensures that the "Originally Published" date meta field is set using the site's configured timezone by replacing the `date` function with WordPress's built in `current_time` function. 
Resolves #93 by ensuring the timezone configured on the site is taken into account when creating the date string.
Changes are available for review in dev.
**Checklist:**
> Replaced date function with current_time

- dev/acf-export.json
- includes/homepage-functions.php
- includes/post-list-functions.php
- Added the ability to specify the number of posts per row in a set of Secondary Stories on the homepage, instead of enforcing a max of 4 per set.  Doing this allows editors to assign all stories in a single set, making it easier to add, remove, and re-order existing stories in the set.  (Previously, you could not drag and drop stories between Secondary Stories rows)
- Adjusted Secondary story columns to start at the -md breakpoint instead of -lg for better visual hierarchy at those screen sizes.
Part of initial sprint to improve Today admin features.
**Checklist:**
> Improved editability of secondary homepage stories

- includes/post-functions.php
- includes/utilities.php
- Added an option to `today_get_post_author_data()` to return original publisher data as an absolute fallback.  Currently, we only set the author name when the function falls back to original publisher data.
- Additionally, `today_get_post_author_data()` will now always return an array with all expected keys (never an empty array).
- Updated `today_get_post_meta_info()` to utilize original publisher data (restoring behavior currently in master).
To make sure we're displaying the author data we want to display/to make it easier to consistently return author data across theme functions.
Reviewed in Dev
**Checklist:**
> Author fallback logic, again

- dev/acf-export.json
- functions.php
- includes/config.php
- includes/header-functions.php
- includes/homepage-functions.php
- includes/pegasus-functions.php
- template-parts/header_content-pegasus_home.php
- template-pegasus_home.php
An initial pass at setting up a new page template and ACF fields for defining Pegasus homepage content.  At this point, the following have been implemented:
- A new page template, `template-pegasus_home.php`, which is partially working/partially dummy content
- ACF fields, specifically for use with the `template-pegasus_home.php` template.  Right now, the featured stories and "in this issue" sections are the only functional sets of fields.
- A header_content template part specifically for the Pegasus homepage, `template-parts/header_content-pegasus_home.php`, with mostly temporary/dummy content
TODOs will be addressed in future PRs.
Part of initial sprint to begin implementing Pegasus articles in Today.
Tested in …
> Pegasus homepage - (rough) first pass

- functions.php
- includes/pegasus-list-functions.php
Adds a `today_sidebar` layout for the Pegasus List Shortcode. 
So that we can use the Pegasus List shortcode to display an issue and featured story in the today sidebar.
Changes viewable in DEV.
**Checklist:**
> Add Pegasus List Today Sidebar Layout

- template-parts/nav.php
Removes the `aria-label` attribute from the navigation toggle in the main menu.
It is not appropriate to have an `aria-label` and inner text that do not match. In this case, the `aria-label` was set to "Toggle navigation" while the button text read "Sections." Because the button has text, the `aria-label` is not necessary, and it was easier to just remove it.
Changes are available in DEV for review.
**Checklist:**
Resolves #140
> Removed aria label from navigation toggle button
