- tag.php
Added tag template to the theme.
Requirements include a solution for displaying a list of stories by tag.
Available for review in Dev.
**Checklist:**
> Added tag template

- dev/acf-export.json
See title.
This setting is not needed or utilized in this theme.
Viewable in dev.
**Checklist:**
> Remove 'Exclude Primary Site Navigation' ACF field

- archive.php
- includes/archive-functions.php
- includes/header-functions.php
- template-parts/header-archive.php
- template-parts/header_content-archive.php
Style updates for the archive page template.
Moves the pagination for archive pages into the header area.
Changes are in dev.
**Checklist:**
> Archives header

- template-parts/header_content-post.php
Removes the subtitle markup from the post header template.
The subtitle field has been replaced by the deck field.
Change can be seen in the development environment.
**Checklist:**
> Removed subtitle from posts

- dev/acf-export.json
Adds an ACF field for indicating if a story should be included on UCF.edu news feeds.
To make it easier to curate news stories on UCF.edu.
Changes are in dev for review.
**Checklist:**
> Added post_main_site_story field

- dev/acf-export.json
- includes/category-functions.php
Adds customizable options and defaults for the events, news, and the resources menu settings. 
Provides more customization options for the fields on the category pages.
Viewable in dev.
**Checklist:**
> Customizable Options for Category ACF Fields

- archive.php
- functions.php
- includes/category-functions.php
- includes/sidebar-functions.php
- page-in-the-news.php
- tag.php
Consolidates display logic for events, UCF in the News, the Resources menu, and other sidebar contents.
Ensures we're consistent with sidebar display logic and reduces redundancy.
**Checklist:**
> Sidebar cleanup

- includes/config.php
Removes the old blogroll "links" admin menu item.
Cleans up the admin menu, and prevents confusion with the Resource Links CPT.
**Checklist:**
> Remove "links" admin menu item

- includes/header-functions.php
- template-parts/header-archive.php
- template-parts/header-category.php
- template-parts/header-post.php
Removed logic for custom header template parts that were no different from the default.
The existing logic in `today_get_header_type()` was returning the same output for all the conditions.  Removing the function and the extra template parts entirely simplifies things.
**Checklist:**
> Simplified header template part logic

- dev/acf-export.json
- single.php
- template-parts/header_content-post.php
Updated default template header to a smaller width.
Client request
Changes have been tested in Dev.
**Checklist:**
> Story updates

- dev/acf-export.json
See title.
Clarifies the Original Publish Date field name and adds some help text describing what editing the Published On field will do.
Changes viewable in dev.
**Checklist:**
> Edit published date field label and description

- category.php
- tag.php
Moves the Events section in the tag and default category templates down below the In The News section. 
Requested in a meeting.
Updates are in dev.
**Checklist:**
> Swap the "In The News" and "Events" Positions

- includes/sidebar-functions.php
Ensures external stories in sidebars have the "External Story" Resource Link Type assigned to them.
Resolves #74 .
**Checklist:**
> Filter sidebar external stories by Resource Link Type term

- includes/excerpts.php
- Updated `today_get_excerpt()` to utilize the UCF WP Theme's new `ucfwp_get_excerpt()` function, which behaves the same as the removed code in this theme.
- Removed `excerpt_more` hook that modifies excerpt truncation ellipses, since the latest version of the UCF WP Theme includes this code now.
Code cleanup/remove redundancies.
**Checklist:**
> Eliminate redundant excerpt code

- includes/utilities.php
Removed the `get_headers` function and refactored to use provided WordPress functions. 
The `get_headers` functions uses `url_fopen` under the hood, which is disallowed on our environments.
Changes are available for review in dev. Opening any of the provided XML feeds without seeing any notices and/or warnings will demonstrate that the code is working.
**Checklist:**
> Notices fix

- includes/features.php
- single.php
- template-category.php
- template-parts/nav.php
- template-twocol.php
- Added unique `aria-label`s to `<article>` elements generated by the theme.
- Removed redundant role and added an `aria-label` for the site navigation `<nav>`.
Resolves #80.
**Checklist:**
> ARIA improvements

- includes/post-functions.php
- template-twocol.php
Updated functions that return a two-column story's "More Headlines", "More About [Category]", and "More About [Tag]" sections to ensure stories are not repeated across these sections.
Resolves #86.
**Checklist:**
> Prevent duplicate stories in two column story sidebars

- includes/post-functions.php
Pushes the tags of the current single post to the dataLayer for Google Tag Manager to use. Also triggers a custom GTM event, which indicates that a tag needs to be processed.
This will allow us to track posts by tag in Google Analytics.
Changes can be viewed in QA by loading stories with or without tags, and viewing the realtime view in Google Analytics for Today QA.
**Checklist:**
> College tags

- CONTRIBUTING.md
Updated the contributing doc to reflect the switch from slack to teams.
Resolved #91 
**Checklist:**
> Updated the contributing doc

- dev/acf-export.json
- includes/post-functions.php
Added the ability to upload an author photo to display alongside other author bio information.
Part of initial sprint of Today admin improvements.
**Checklist:**
> Author photos

- dev/acf-export.json
- includes/post-functions.php
- includes/utilities.php
**Requires https://github.com/UCF/Today-Utilities/pull/36**
- Modified author data fields for posts to also be shared with Statements.  An existing Author term can now be assigned to posts/Statements instead of custom author data.
- Added fields for defining a title, photo and bio to Author terms.
- Added new helper function, `today_get_post_author_data()`, that returns an array of author information for the provided post.  If the post has an Author term assigned to it, that Author's related data is returned; else, if the post has custom author data set, that data is returned instead.
- Updated post author bio display logic (`today_get_post_author_bio()`) to use Author term data if necessary.
- Updated post author name filtering logic (`today_filter_post_author_name()`) to …
> Author taxonomy support

- dev/acf-export.json
See title
We only really need custom author support for backward compatibility on standard posts; and supporting custom author values for this post type would over-complicate how the new statements page filtering by author will work.
**Checklist:**
> Removed custom author support on Statements

- includes/amp-functions.php
Added post author if ACF author empty
Client request
Tested in Dev
- [] New feature (non-breaking change which adds functionality)
**Checklist:**
> Added post author if ACF author empty

- functions.php
- includes/utilities.php
- Prepended theme dir to required files in functions.php
- Updated `today_get_post_author_data()` to only return original publisher data as an absolute fallback for standard posts (_not_ Statements)
- Cleanup
- To ensure author behavior is consistent for Statements on the frontend and in the REST API
Reviewed in Dev
**Checklist:**
> Restricted Statement author fallbacks; file includes cleanup

- dev/acf-export.json
See title.
Requested by Roger.
**Checklist:**
> Updated Statements to require an Author term to be assigned

- includes/amp-functions.php
Updated amp author logic to use today_get_post_author_data method
To support new ACF fields
Tested in Dev
**Checklist:**
> Updated amp author logic to use today_get_post_author_data method

- includes/utilities.php
Modified the `post_author_type` check in `today_get_post_author_data()` to correctly handle the type of author Statements have.
`today_get_post_author_data()` should never be allowed to return nonexistent custom author data for Statements.
**Checklist:**
> Fixed post_author_type logic for statements

- archive-ucf_statement.php
- functions.php
- includes/statements-functions.php
Created an archive page for statements CPT.
Client request
Tested in DEV
**Checklist:**
> Added Statement archive page

- includes/pegasus-list-functions.php
- includes/post-functions.php
Resolves #141. 
In general, making large areas of text all in uppercase is not great for readability. Our auditing tool expects anything within a paragraph tag, or a wrapping div tag, to contain a large amount of content and flags instances where those elements have a text-transform of uppercase. After reviewing, we found that in both of these instances, we should (1) not be using a paragraph tag when the content can really be in a span and (2) removed uppercase styling from what can be a lengthy line of text.
Changes are available for review in DEV.
**Checklist:**
> Accessibility changes

- includes/post-functions.php
See title.
Resolves #153 
Tested in Dev.
**Checklist:**
> Removed italics on author bios

- includes/sidebar-functions.php
- tag.php
Update the "In the News" sidebar on the tag template to show only external stories that have that tag. If a particular tag does not have any external stories, the tag filter will be removed and the most recent 5 external stories will be shown.
This allows the tag template pages to be more contextual showing specific stories that match the tag being browsed.
Changes have been tested locally and demonstrated on our Slack.
**Checklist:**
> Hf in the news tags

- includes/features.php
Small update to the other feature-title layouts to change the h2 to an paragraph tag.
SEO!
Changes have been verified locally.
**Checklist:**
> Update the other feature title layouts
